apiVersion: v2
name: contact-enrichment
description: Contact Enrichment Platform (Java) - Helm chart
version: 0.2.0
appVersion: "1.0.0"
type: application
annotations:
  artifacthub.io/links: |
    - name: source
      url: https://github.com/thomasvincent/contact-enrichment-tos
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
