{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contact-enrichment.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end -}}
