{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "contact-enrichment.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress: {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
  egress: {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
{{- end }}
