{{- if and .Values.secrets .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contact-enrichment.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
