{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contact-enrichment.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
