apiVersion: v1
kind: Service
metadata:
  name: {{ include "contact-enrichment.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "contact-enrichment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
